version: "3.7"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    tty: true